# Generated by Django 2.2.5 on 2019-09-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasePersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ap_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('ap_materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('domicilio', models.CharField(max_length=300, verbose_name='Domicilio')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('celular', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular')),
                ('fech_nac', models.DateField(verbose_name='Fecha Nacimiento')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('basepersona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.BasePersona')),
                ('estado', models.BooleanField(default=True)),
            ],
            bases=('persona.basepersona',),
        ),
    ]
