# Generated by Django 2.2.5 on 2019-09-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepersona',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='basepersona',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Telefono'),
        ),
    ]
