# Generated by Django 2.2.5 on 2019-10-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20190917_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepersona',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=10, verbose_name='Sexo'),
        ),
    ]
