# Generated by Django 2.2.5 on 2019-09-18 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0002_auto_20190917_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=3)),
                ('talla', models.PositiveSmallIntegerField()),
                ('estatura', models.PositiveSmallIntegerField()),
                ('motivo', models.TextField()),
                ('examen_fisico', models.TextField()),
                ('examen_laboratorio', models.TextField()),
                ('diagnostico', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Paciente')),
            ],
        ),
    ]
