# Generated by Django 2.2.5 on 2019-09-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_auto_20190928_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='estatura',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
