# Generated by Django 2.2.5 on 2019-09-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_auto_20190928_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='peso',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
