# Generated by Django 2.2.5 on 2019-10-05 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_auto_20191004_2231'),
        ('consulta', '0005_auto_20190928_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaDescripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicacion', models.TextField(max_length=300)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.ManyToManyField(blank=True, null=True, to='consulta.RecetaDescripcion')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consulta.Receta'),
        ),
    ]
