# Generated by Django 2.2.5 on 2019-10-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0007_receta_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='descripcion',
            field=models.ManyToManyField(blank=True, to='consulta.RecetaDescripcion'),
        ),
    ]
