# Generated by Django 2.2.5 on 2019-10-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermedad',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
