# Generated by Django 2.2.5 on 2019-09-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='observacion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
