# Generated by Django 2.2.5 on 2019-09-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_auto_20190921_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='inicio_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='inicio',
            field=models.DateField(),
        ),
    ]
