# Generated by Django 2.2.5 on 2019-09-22 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_auto_20190921_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='inicio_time',
        ),
    ]
