# Generated by Django 2.2.5 on 2019-09-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0004_remove_cita_inicio_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='inicio',
            field=models.DateTimeField(),
        ),
    ]
