# Generated by Django 2.2.5 on 2019-09-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0005_auto_20190921_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='color',
            field=models.CharField(choices=[('#fcf12e', 'Amarillo'), ('#ff0000', 'Rojo'), ('#5fb5f3', 'Azul'), ('#51ee4d', 'Verde')], default='#51ee4d', max_length=50, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='cita',
            name='status',
            field=models.CharField(choices=[(1, 'Activo'), (2, 'Cancelado'), (3, 'No Asistio')], default=1, max_length=50, verbose_name='Estado'),
        ),
    ]
